### PR TITLE
New ServiceDescriptorMergeStrategy.Add logic

### PR DESCRIPTION
**Pull request by Thundarr1974**
- Upgrade to net6.0
- Incorporated new ServiceDescriptorMergeStrategy.Add as default
- Replaced ServiceConstructorAttribute with existing ActivatorUtilitiesConstructorAttribute
- Added convenience RegisterXYZ attributes

### CODE REVIEW

**Comment by Flavien** [comment]
Thanks for submitting this PR. I've gone through it, and I believe some of the changes you made make sense:
- I didn't know `Add` could be used to then obtain an array of all the registered services implementing a specific type. So it definitely makes sense to add this. Only minor point, we need to add unit tests to ensure any new functionality is covered.
- It makes sense to upgrade to .NET 6.0 as .NET 5.0 is coming out of support in about a month. The library multitargets .NET Standard 2.0 anyway.
- This is a minor breaking change, but it does make sense to rename `Skip` to `TryAdd` since this is what the method is called in `Microsoft.Extensions.DependencyInjection` and therefore will be less confusing to users.

On the changes I have issues with:
- On the `RegisterSingletonAttribute`, `RegisterScopedAttribute`, `RegisterTransientAttribute`, `RegisterBackgroundAttribute` variants. I guess it saves a few characters, but technically we would need to add the same four attributes for `RegisterFactory`. So we're adding a total of eight attributes that really are just a variation of already existing attributes. That also means we would need to add at least one unit test for each. So I'm not really in favour of this. But what we can do is add a default of `ServiceLifetime.Scoped` for the `scope` argument to `RegisterServiceAttribute` and `RegisterFactoryAttribute`, so that in most cases, you won't have to specify it.
If you feel these shorthand attributes are helpful, my suggestion would be to either make a new package referencing `Quickwire` adding these helpers (like `Quickwire.Helpers`), or just simply define them in your project.
- Removing `Inherited = false`: Inheritance is deliberately disabled here, without it, if you were to decorate a class with `[RegisterService]`, any derived class would automatically get registered as well, which sometimes may not be desired. I prefer things to be explicit. If you want to register a child class, you have to explicitly set the attribute on it. Same reason behind not using `inherit: true` with `type.GetCustomAttributes<RegisterServiceAttribute>()`
- It is true that `ActivatorUtilitiesConstructorAttribute` fills a similar purpose as `ServiceConstructorAttribute`, however my concern is that they do work with two different sets of APIs, and `ActivatorUtilities` and `ServiceActivator` resolve constructor parameters differently (e.g. `InjectConfiguration` works with `ServiceActivator` but not `ActivatorUtilities`), so you could imagine a valid scenario where someone would want to use one constructor for `ActivatorUtilities` and a different constructor for `ServiceActivator`. This is not possible if they both rely on the same attribute.
- The three assembly dependencies (`Microsoft.Extensions.Configuration.Abstractions`, etc.) are on version `3.1` on purpose as this means the library can be used with .NET 3.1+. But if the runtime you have installed is 6.0, it will automatically make use of 6.0. 3.1 just indicates the minimum allowed version.
- Removing nullability on the return value for: `delegate object? Factory(object?[] arguments)`: Even though that doesn't necessarily make a lot of sense to do that, it is possible for a factory method to return null, so the return type should be `object?`.

So I will push a commit to your branch to adjust the PR to take this into consideration (and add tests) if that's ok with you, then we can merge these changes.

**Comment by Flavien** [comment]
Actually, I just noticed a problem with targeting .NET 6.0: it breaks `InjectAllInitOnlyProperties` functionality on .NET 5.0 (you can verify this by running the unit tests while targeting .NET 5.0). There is no obvious benefit to upgrading to .NET 6.0 (it will always use the highest version available at runtime anyway), so not worth breaking backwards compatibility with .NET 5.0, so I will revert to .NET 5.0.

**Comment by Thundarr1974** [comment]
Thanks Flavien! My PR was mostly suggestions, but here are some observations for a few of those changes:

1. I added the convenience attributes to also eliminate having to declare "using Microsoft.Extensions.DependencyInjection". An ok workaround is to leverage the new "global using" to reduce the clutter, so makes sense to drop these.
2. I removed the nullability on the Factory delegate b/c ServiceDescriptor does not appear to support returning a null object from the factory: 
image
3. My project has a security requirement to only use .net6 packages so I'll have to stick with the fork for now. If I get some free time I'll look at resolving InjectAllInitOnlyProperties under 6...

**Comment by Flavien** [comment]
On (3), you might want to double check the relevance of this requirement. Normally the target framework for a NuGet package only affect which API surface it is targeting, but the implementation that is actually used at runtime only depends on the target framework of the top level application.

You can verify this by creating a project targeting .NET 6.0 and running this:

``` csharp
using Microsoft.Extensions.DependencyInjection;
using Quickwire;
using System.Reflection;

// Ensure assemblies get loaded
Type? type1 = typeof(ServiceScanner);
Type? type2 = typeof(ServiceCollection);

foreach (Assembly dependency in AppDomain.CurrentDomain.GetAssemblies())
{
    Console.WriteLine(dependency.FullName);
}
```

This gives (redacting some of the output):
```
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Console, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Quickwire, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null
System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```
You can see that despite targeting .NET 5.0 and having dependencies set to 3.1, the actual runtime assemblies are all 6.0.

**Comment by Thundarr1974** [comment]
> On (3), you might want to double check the relevance of this requirement. Normally the target framework for a NuGet package only affect which API surface it is targeting, but the implementation that is actually used at runtime only depends on the target framework of the top level application.
> 
> You can verify this by creating a project targeting .NET 6.0 and running this:
> 
> ```cs
> using Microsoft.Extensions.DependencyInjection;
> using Quickwire;
> using System.Reflection;
> 
> // Ensure assemblies get loaded
> Type? type1 = typeof(ServiceScanner);
> Type? type2 = typeof(ServiceCollection);
> 
> foreach (Assembly dependency in AppDomain.CurrentDomain.GetAssemblies())
> {
>     Console.WriteLine(dependency.FullName);
> }
> ```
> 
> This gives (redacting some of the output):
> 
> ```
> System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
> System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> System.Console, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
> Quickwire, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null
> System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
> ```
> 
> You can see that despite targeting .NET 5.0 and having dependencies set to 3.1, the actual runtime assemblies are all 6.0.

Thanks for the info. The policy isn't mine though :) It's a client company's InfoSec standard policy for any OSS packages.

**Pull request merged**
